# Generated by Django 4.2.6 on 2023-10-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
            ],
        ),
    ]
