# Generated by Django 4.2.6 on 2023-10-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
